### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [GrantSeltzer/seltzer.zsh-theme#2]
I'd like to add this to the [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins) list but prefer to add themes with screenshots so people can see what they look like without having to install them.

**Comment by grantseltzer** [comment]
Hey @unixorn that sounds awesome! There's a screen shot [already](https://github.com/GrantSeltzer/seltzer.zsh-theme/blob/master/zsh.png) but it should probably be in the README. Here's another, hope that works!
 
![image](https://user-images.githubusercontent.com/10857349/32556556-c1b6d33e-c46d-11e7-89bb-6c2c3948a1cb.png)

**Comment by grantseltzer** [comment]
Hope that works @unixorn!

**Comment by unixorn** [comment]
Thanks. Adding it as of https://github.com/unixorn/awesome-zsh-plugins/pull/342
